name: Generate and Deploy Animation

on:
  # Run every 24 hours automatically
  schedule:
    - cron: "0 */24 * * *" 
  
  # Allow manual execution of the workflow
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate_animation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate the snake game animation from GitHub contributions
      - name: Generate Contribution Grid Snake Animation (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  deploy_animation:
    needs: generate_animation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Deploy the generated SVG animation to the 'output' branch
      - name: Deploy Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
